# Generated by Django 5.0.14 on 2026-09-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='monthly_query_limit',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
