# Generated by Django 5.0.14 on 2026-09-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='feedback',
            field=models.SmallIntegerField(choices=[(-1, 'Not helpful'), (0, 'No feedback'), (1, 'Helpful')], default=0),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
